jobs:
  approve:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Approve
      run: echo For security reasons, all pull requests need to be approved first
        before running any automated CI.
  build:
    environment:
      name: Integrate Pull Request
    needs:
    - approve
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout PR
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      name: Setup jdk
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      env:
        NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.ORG_NETFLIXOSS_PASSWORD }}
        NETFLIX_OSS_REPO_USERNAME: ${{ secrets.ORG_NETFLIXOSS_USERNAME }}
        NETFLIX_OSS_SIGNING_KEY: ${{ secrets.ORG_SIGNING_KEY }}
        NETFLIX_OSS_SIGNING_PASSWORD: ${{ secrets.ORG_SIGNING_PASSWORD }}
      name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: --info --stacktrace build -x test snapshot
    - continue-on-error: true
      name: Create PR Comment String
      run: 'src=${GITHUB_WORKSPACE}/build/versions.txt

        dest=${GITHUB_WORKSPACE}/build/versions2.txt

        echo ''resolutionStrategy {'' > $dest

        awk ''{print "    force \"" $0 "\""}'' $src >> $dest

        echo ''}'' >> $dest

        echo "PR_STR<<EOF" >> $GITHUB_ENV

        cat ${dest} >> $GITHUB_ENV

        echo ''EOF'' >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Upload
      uses: mshick/add-pr-comment@v2
      with:
        allow-repeats: false
        message: '## Uploaded Artifacts

          To use these artifacts in your Gradle project, paste the following lines
          in your build.gradle.

          ```

          ${{ env.PR_STR }}

          ```

          '
        message-id: ${{ github.event.number }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: Publish snapshot to NetflixOSS and Maven Central
on:
  repository_dispatch:
    types: trigger-ga___nebula-snapshot.yml
