jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Setup jdk
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      env:
        NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.ORG_NETFLIXOSS_PASSWORD }}
        NETFLIX_OSS_REPO_USERNAME: ${{ secrets.ORG_NETFLIXOSS_USERNAME }}
        NETFLIX_OSS_SIGNING_KEY: ${{ secrets.ORG_SIGNING_KEY }}
        NETFLIX_OSS_SIGNING_PASSWORD: ${{ secrets.ORG_SIGNING_PASSWORD }}
      if: contains(github.ref, '-rc.')
      name: Publish candidate
      uses: gradle/gradle-build-action@v2
      with:
        arguments: -Prelease.useLastTag=true -x test candidate
    - continue-on-error: true
      env:
        NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.ORG_NETFLIXOSS_PASSWORD }}
        NETFLIX_OSS_REPO_USERNAME: ${{ secrets.ORG_NETFLIXOSS_USERNAME }}
        NETFLIX_OSS_SIGNING_KEY: ${{ secrets.ORG_SIGNING_KEY }}
        NETFLIX_OSS_SIGNING_PASSWORD: ${{ secrets.ORG_SIGNING_PASSWORD }}
        NETFLIX_OSS_SONATYPE_PASSWORD: ${{ secrets.ORG_SONATYPE_PASSWORD }}
        NETFLIX_OSS_SONATYPE_STAGING_PROFILE_ID: c3547130240327
        NETFLIX_OSS_SONATYPE_USERNAME: ${{ secrets.ORG_SONATYPE_USERNAME }}
      if: (!contains(github.ref, '-rc.'))
      name: Publish release
      uses: gradle/gradle-build-action@v2
      with:
        arguments: -Prelease.useLastTag=true -x test final
name: Publish candidate/release to NetflixOSS and Maven Central
on:
  repository_dispatch:
    types: trigger-ga___nebula-publish.yml
